config/routes.rb
Rails.application.routes.draw do
    
  root 'sessions#home'
  
  get '/signup' => "users#new"
  
  #login routes
  get '/login' => "sessions#new"
  post '/login' => "sessions#create"

  #logout route
  delete '/logout' => "sessions#destroy"
  
  #omniauth callback route
  get '/auth/google_oauth2/callback' => 'sessions#omniauth'

  #if you want more than one third party verification, you need to have a dynamic :provider...
  # get '/auth/:provider/callback' => 'sessions#omniauth'
  
  resources :users
  
  resources :teachers do
    resources :assignments, only: [:new, :create, :index]
    
  end
  
  resources :students do
    resources :assignments, only: [:index]
  end
  
  resources :assignments

  #scope method routes
  get '/alpha' => 'assignments#alpha'
  get '/overdue_assignments' => 'assignments#overdue_assignments'
end

app/models/assignment.rb
class Assignment < ApplicationRecord
  belongs_to :teacher
  belongs_to :student

  validates :title, :content, :due_date, presence: true

  
  scope :alpha, -> { order (:content) }  

  scope :overdue_assignments, -> (date) { where("due_date < ?", date) && where("completed == false") }

  # def self.search(search)
  #   if search
  #     stu = Student.find_by(first_name: search)
      
  #     if stu
  #       Student.where("first_name LIKE ?", search) 
  #     else
  #       @assignments = Assignment.all
  #     end
  #   else
  #     @assignments = Assignment.all
  #   end
  # end
end

app/controllers/assignments_controller.rb
class AssignmentsController < ApplicationController
    before_action :set_assignment, only: [:show, :edit, :update]
    before_action :redirect_if_not_logged_in

    def index
        #in order to check for nesting, check for foreign key
        if params[:student_id] && @student = Student.find_by_id(params[:student_id]) #add the find_by to return nil if they look for non-existent student
            # then it will be nested
            @assignments = @student.assignments
        else
            @assignments = Assignment.all
        end
    end

    def new
        if params[:teacher_id] && @teacher = Teacher.find_by_id(params[:teacher_id])
            @assignment = @teacher.assignments.build
        else
            #not sure I would need this as functionally, only a teacher can create an assignment
            @assignment = Assignment.new
        end
    end

    def create
        @assignment = Assignment.new(assignment_params)
        if @assignment.save   
            redirect_to assignment_path(@assignment)
        else    
            render :new
        end
    end

    def show
    end

    def edit
    end

    def update
        @assignment.update(assignment_params)
        flash[:message] = "You have updated this Assignment"
        redirect_to assignment_path(@assignment)
    end

    def destroy
        @assignment = Assignment.find(params[:id]).destroy
        redirect_to user_path(current_user)
    end

    def overdue_assignments
        @assignments = Assignment.overdue_assignments(DateTime.now)
    end

    private

    def assignment_params
        params.require(:assignment).permit(:title, :content, :completed, :letter_grade, :due_date, :teacher_id, :student_id )
    end

    def set_assignment
        @assignment = Assignment.find_by(id: params[:id]) 
        redirect_to user_path(current_user) if !@assignment
    end
end

app/helpers/assignments_helper.rb
module AssignmentsHelper


end

app/views/assignments/alpha.html.erb
<% if @assignments == [] %>
    <h2>No current assignments. </h2>
<% else %>
    <% @assignments.each do |assign| %>
        <h4>Assignment Title: <%= assign.title if assign.title %></h4>
        <h4>Content of Assignment: <%= assign.content if assign.content %></h4>
        <h4>Assigning Teacher: <%= full_name(assign.teacher) if assign.teacher %></h4>
        <h4>Student Assigned: <%= full_name(assign.student) if assign.student %></h4>
    <br>
    <% end %>
<% end %>

app/views/assignments/edit.html.erb
<h1>Update This Assignment</h1>

<%= render partial: "layouts/errors", locals: {object: @assignment} %>
<%# this will render the errors partial and then send our original variable to the "object" variable in the form%>

<%= form_for @assignment do |f| %>
    <%= f.label :title %>
    <%= f.text_field :title %>
    <br>
    <%= f.label :content %>
    <%= f.text_area :content %>
    <br>
    <%= f.label :due_date %>
    <%= f.date_field :due_date %>
    <br>
    <%= f.label :completed %>
    <%= f.check_box :completed %>
    <br>
    <%= f.label :letter_grade %>
    <%= f.text_field :letter_grade %>
    <br>
    <%= f.label :teacher_id, "Assigning Teacher" %>
    <%= f.collection_select :teacher_id, current_user.teachers, :id, :full_name, prompt: true %>
    <br>
    <br>
    <%= f.label :student_id, "Students who will be assigned" %>
    <%= f.collection_select :student_id, current_user.students, :id, :full_name, prompt: true %>
    <br>
    <br>
    <%# f.collection_select :teacher_id, Teacher.all, :id, :first_name %>   
    <%# you can add the hidden field for setting up user_id but that leaves %>
    <%# a vulnerability to someone changing the hidden field, better in the controller sometimes %>
    <%= f.submit "Update Assignment" %>

<% end %>

app/views/assignments/index.html.erb
<h1> Assignments Index </h1>

<% if @assignments == [] %>
    <h6>No current assignments. </h6>
<% else %>

<table class="table table-striped table-hover">
  <thead class="table-dark" >
    <tr>
      
      <th>Assignment Title</th>
      <th>Assignment Content</th>
      <th>Student Name</th>
      <th>Assignment Due Date</th>
      <th>Completed?</th>
      <th>Assignment Grade</th>
      <th colspan="6"></th>
    </tr>
  </thead>

  <tbody>
    <% @assignments.each do |assignment| %>
      <tr>
        <td><%= assignment.title %></td>
        <td><%= assignment.content %></td>
        <td><%= full_name(assignment.student) %></td>
        <td><%= assignment.due_date.strftime("%m/%d/%y") %></td>
        <td><%= assignment.completed %></td>
        <td><%= assignment.letter_grade %></td>
        <td><%= link_to "Assignment Page", assignment_path(assignment), class:"btn btn-success btn-sm" %></td>
        <td><%= link_to "Student Page", student_path(assignment.student), class:"btn btn-success btn-sm" %></td>  
        <td><%= link_to "Teacher Page", teacher_path(assignment.teacher), class:"btn btn-success btn-sm" %></td> 
      </tr>
    <% end %>
  </tbody>
</table>
<% end %>

app/views/assignments/new.html.erb
<h1>Add a New Assignment</h1>

<%= render partial: "layouts/errors", locals: {object: @assignment} %>
<%# this will render the errors partial and then send our original variable to the "object" variable in the form%>

<%= form_for([@assignment.teacher, @assignment]) do |f| %>
    <%# adding the @teacher allows for nesting and will directly assign this assignment to @teacher %>
    <%= f.label :title %>
    <%= f.text_field :title %>
    <br>
    <%= f.label :content %>
    <%= f.text_area :content %>
    <br>
    <%= f.label :due_date %>
    <%= f.date_field :due_date %>
    <br>
    <br>
    <% if !@assignment.teacher %>
        <%# removes drop down if there is a teacher for this assignment aka with nesting%>
        <%= f.label :teacher_id, "Assigning Teacher" %>
        <%= f.collection_select :teacher_id, current_user.teachers, :id, :full_name, prompt: true %>
        <br>
        <br>
    <% else %>
        <%= f.hidden_field :teacher_id %>
    <% end %>
    
    <%= f.label :student_id, "Student who will be assigned" %>
    <%= f.collection_select :student_id, current_user.students, :id, :full_name, prompt: true %>
    <br>
    <br>
    <%# f.collection_select :teacher_id, Teacher.all, :id, :first_name %>   
    <%# you can add the hidden field for setting up user_id but that leaves %>
    <%# a vulnerability to someone changing the hidden field, better in the controller sometimes %>
    <%= f.submit "Create a new Assignment" %>

<% end %>

app/views/assignments/overdue_assignments.html.erb
<h1> Overdue Assignments </h1>
<br>
<br>
<% if @assignments == [] %>
    <h6> There are currently no overdue assignments. </h6>
<% else %>
<table class="table table-striped table-hover">
  <thead class="table-dark" >
    <tr>
      <th>Assignment Title</th>
      <th>Assignment Content</th>
      <th>Student Name</th>
      <th>Teacher Name</th>
      <th>Assignment Due Date</th>
      <th>Days Overdue</th>
      <th colspan="5"></th>
    </tr>
  </thead>

  <tbody>
    <% @assignments.each do |assignment| %>
      <tr>
        <td><%= assignment.title %></td>
        <td><%= assignment.content %></td>
        <td><%= full_name(assignment.student) %></td>
        <td><%= full_name(assignment.teacher) %></td>
        <td><%= assignment.due_date.strftime("%m/%d/%y") %></td>
        <td><strong><%= TimeDifference.between(Date.today, assignment.due_date).in_days.to_i %></strong></td>
        

        <td><%= link_to "Assignment Page", assignment_path(assignment), class:"btn btn-success btn-sm" %></td>
        <td><%= link_to "Student Page", student_path(assignment.student), class:"btn btn-success btn-sm" %></td>  
        <td><%= link_to "Teacher Page", teacher_path(assignment.teacher), class:"btn btn-success btn-sm" %></td> 
      </tr>
    <% end %>
  </tbody>
</table>
<% end %>

app/views/assignments/show.html.erb
<h1> Assignment Show Page </h1>

<h6><strong>Assignment Title:</strong> <%= @assignment.title %> </h6>
<h6><strong>Assignment content:</strong> <%= @assignment.content %> </h6>
<h6><strong>Due Date:</strong> <%= @assignment.due_date.strftime("%m/%d/%y") %></h6>
<h6><strong>Assigment Completed?:</strong> <%= @assignment.completed %></h6>
<h6><strong>Assigment Grade:</strong> <%= @assignment.letter_grade %></h6>
<br>
<br>

<h6><strong>Assigning Teacher:</strong> <%= link_to full_name(@assignment.teacher), teacher_path(@assignment.teacher.id), class:"btn btn-success btn-sm" %> </h6>
<h6><strong>Assigned Student:</strong> <%= link_to full_name(@assignment.student), student_path(@assignment.student.id), class:"btn btn-success btn-sm" %> </h6>



<br>
<br>
<%= link_to "Edit This Assignment", edit_assignment_path(@assignment), class:"btn btn-info btn-sm" %>
<br>
<br>
<%= link_to "Delete Assignment", @assignment, method: :delete, data: { confirm: "Please confirm deletion of this assignment"}, class:"btn btn-dark btn-sm" %>
<br>