config/routes.rb
Rails.application.routes.draw do
    
  root 'sessions#home'
  
  get '/signup' => "users#new"
  
  #login routes
  get '/login' => "sessions#new"
  post '/login' => "sessions#create"

  #logout route
  delete '/logout' => "sessions#destroy"
  
  #omniauth callback route
  get '/auth/google_oauth2/callback' => 'sessions#omniauth'

  #if you want more than one third party verification, you need to have a dynamic :provider...
  # get '/auth/:provider/callback' => 'sessions#omniauth'
  
  resources :users
  
  resources :teachers do
    resources :assignments, only: [:new, :create, :index]
    
  end
  
  resources :students do
    resources :assignments, only: [:index]
  end
  
  resources :assignments

  #scope method routes
  get '/alpha' => 'assignments#alpha'
  get '/overdue_assignments' => 'assignments#overdue_assignments'
end

app/models/user.rb
class User < ApplicationRecord
    validates :username, uniqueness: true, presence: true
    validates :email, presence: true, uniqueness: true
    validates :password, presence: true
    
    has_secure_password #this takes care of initial password validations but won't do everything for password confirmation field
    
    has_many :teachers
    has_many :students

    def self.from_omniauth(auth)
      where(uid: auth.info.uid).first do |user|
        #removed "_or_initialize" so a new user wouldn't be instantiated
        user.username = auth.info.name
        user.email = auth.info.email
        user.password = SecureRandom.hex
      end
    end


end

app/controllers/users_controller.rb
class UsersController < ApplicationController
    def new
        @user = User.new
    end

    def create
        @user = User.new(user_params)
        if @user.save
            session[:user_id] = @user.id
            redirect_to user_path(@user)
        else
            redirect_to signup_path
        end
    end

    def show
        @user = User.find(params[:id])
    end

    private

    def user_params
        params.require(:user).permit(:username, :email, :password, :school)
    end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/new.html.erb
<h1> Sign Up for Principal Principle: </h1>
<h3> School Management Tool </h3>
<br>
<br>

<%= render partial: "layouts/errors", locals: {object: @user} %>
<%# this will render the errors partial and then send our original variable to the "object" variable in the form%>

<%= form_for @user do |f| %>
    <%= f.label :username %>
    <%= f.text_field :username %>
    <br>
    <br>
    <%= f.label :email %>
    <%= f.email_field :email, required:true %>
    <br>
    <br>
    <%= f.label :password %>
    <%= f.password_field :password, required:true %>
    <br>
    <br>
    <%= f.label :school %>
    <%= f.text_field :school %>
    <br>
    <br>
    
    <%= f.submit "Create Your New School Admin Experience" %>

<% end %>

app/views/users/show.html.erb
<h1>Principal Principle Admin Page</h1>
<h3> School: <%= @user.school %></h3>

<h6><strong>Administrator Name:</strong> <%=@user.username%></h6>
<h6><strong>Administrator Email:</strong> <%=@user.email%></h6>
<p><%= @user.school %> currently has <%= @user.teachers.count %> teachers and <%= @user.students.count %> students.</p>

<%= flash[:message] if flash[:message] %>

<%= link_to "Teacher Index Page", teachers_path, class:"btn btn-success btn-sm"%>

<h5> Current Teachers</h5>

<table class="table table-striped table-hover">
  <thead class="table-dark" >
    <tr>
      <th>First name</th>
      <th>Last name</th>
      <th>Subject</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @user.teachers.each do |teacher| %>
      <tr>
        <td><%= teacher.first_name %></td>
        <td><%= teacher.last_name %></td>
        <td><%= teacher.subject %></td>
        <td><%= link_to "#{teacher.first_name}'s Show Page", teacher_path(teacher), class:"btn btn-success btn-sm" %></td>
        <td><%= link_to 'Edit', edit_teacher_path(teacher), class:"btn btn-info btn-sm" %></td>
        <td><%= link_to 'Destroy', teacher, method: :delete, data: { confirm: "Please confirm deletion of #{teacher.first_name}" }, class:"btn btn-dark btn-sm" %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<h5>Current Students</h5>

<table class="table table-striped table-hover">
  <thead class="table-dark" >
    <tr>
      <th>First name</th>
      <th>Last name</th>
      <th>Grade Level</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @user.students.each do |student| %>
      <tr>
        <td><%= student.first_name %></td>
        <td><%= student.last_name %></td>
        <td><%= student.grade_level %></td>
        <td><%= link_to "#{student.first_name}'s Show Page", student_path(student), class:"btn btn-success btn-sm" %></td>
        <td><%= link_to 'Edit', edit_student_path(student), class:"btn btn-info btn-sm" %></td>
        <td><%= link_to 'Destroy', student, method: :delete, data: { confirm: "Please confirm deletion of #{student.first_name}" }, class:"btn btn-dark btn-sm" %></td>
      </tr>
    <% end %>
  </tbody>
</table>