config/routes.rb
Rails.application.routes.draw do
    
  root 'sessions#home'
  
  get '/signup' => "users#new"
  
  #login routes
  get '/login' => "sessions#new"
  post '/login' => "sessions#create"

  #logout route
  delete '/logout' => "sessions#destroy"
  
  #omniauth callback route
  get '/auth/google_oauth2/callback' => 'sessions#omniauth'

  #if you want more than one third party verification, you need to have a dynamic :provider...
  # get '/auth/:provider/callback' => 'sessions#omniauth'
  
  resources :users
  
  resources :teachers do
    resources :assignments, only: [:new, :create, :index]
    
  end
  
  resources :students do
    resources :assignments, only: [:index]
  end
  
  resources :assignments

  #scope method routes
  get '/alpha' => 'assignments#alpha'
  get '/overdue_assignments' => 'assignments#overdue_assignments'
end

app/models/teacher.rb
class Teacher < ApplicationRecord
  belongs_to :user
  has_many :assignments, :dependent => :destroy
  has_many :students, through: :assignments, :dependent => :destroy

  validates :first_name, :last_name, :subject, :hobby, presence: true

  def self.search(params)
    where("LOWER(first_name) LIKE ?", "%#{params}%")
  end

  def full_name
    fn = self.first_name + " " + self.last_name
    fn.titleize
  end

end

app/controllers/teachers_controller.rb
class TeachersController < ApplicationController
    before_action :set_teacher, only: [:show, :edit, :update]
    before_action :redirect_if_not_logged_in
    

    def index
        @teachers = current_user.teachers
        if params[:search] && !params[:search].empty?
            @teachers = Teacher.search(params[:search])
        else
            @teachers = current_user.teachers   
        end
    end
    
    def new
        @teacher = Teacher.new
    end

    def create
        @teacher = current_user.teachers.build(teacher_params)
        if @teacher.save
            flash[:message]= "You have a new teacher!"
            redirect_to user_path(@teacher.user.id)
        else
            render :new
        end 
    end

    def show
    end

    def edit    
    end

    def update
        @teacher.update(teacher_params)
        flash[:message] = "You have updated #{full_name(@teacher)}"
        redirect_to user_path(@teacher.user.id)
    end

    def destroy
        @teacher = Teacher.find(params[:id]).destroy
        redirect_to user_path(current_user)
    end

    private

    def teacher_params
        params.require(:teacher).permit(:first_name, :last_name, :subject, :hobby, :user_id, :search)
    end

    def set_teacher
        @teacher = Teacher.find_by(id: params[:id]) 
        redirect_to user_path(current_user) if !@teacher
    end
end

app/helpers/teachers_helper.rb
module TeachersHelper


    #Was going to create a method for hash creation for list of uniq students and their assignments...

    # def students_and_their_assignments(teacher)
    #     stud_ass = Hash.new()
    #     teacher.students.each do |student|
    #         stud_ass = Hash.new({full_name(student): student.})
    #     end

    # end
end

app/views/teachers/_form.html.erb
<%= form_for @teacher do |f| %>
    <%= f.label :first_name %>
    <%= f.text_field :first_name %>
    <br>
    <%= f.label :last_name %>
    <%= f.text_field :last_name %>
    <br>
    <%= f.label :subject %>
    <%= f.text_field :subject %>
    <br>
    <%= f.label :hobby %>
    <%= f.text_area :hobby %>
    <br>
    <%# you can add the hidden field for setting up user_id but that leaves %>
    <%# a vulnerability to someone changing the hidden field, better in the controller sometimes %>
    <%= f.submit %>
    <%#button_text is the helper method I made to have either Add or Upate%>
<% end %>

app/views/teachers/edit.html.erb
<h1>Edit <%= full_name(@teacher) %>'s Information</h1>

<%= render partial: "layouts/errors", locals: {object: @teacher} %>
<%# this will render the errors partial and then send our original variable to the "object" variable in the form%>

<%= render 'form' %>

app/views/teachers/index.html.erb
<h1> Teacher Index </h1>


<%= form_tag("/teachers", method: "get") do %>
  <%= label_tag(:search, "Search for a Teacher") %>
  <%= text_field_tag :search, params[:search] %>
  <%= submit_tag "Search" %>
<% end %>
<br>

<% if @teachers == [] %>
    <h6>No current teachers. </h6>
<% else %>

<table class="table table-striped table-hover">
  <thead class="table-dark" >
    <tr>
      
      <th>Teacher First Name</th>
      <th>Teacher Last Name</th>
      <th>Teacher Subject</th>
      <th>Hobby</th>
      <th colspan="4"></th>
    </tr>
  </thead>

  <tbody>
    <% @teachers.each do |teacher| %>
      <tr>
        <td><%= teacher.first_name %></td>
        <td><%= teacher.last_name %></td>
        <td><%= teacher.subject %></td>
        <td><%= teacher.hobby %></td>
      </tr>
    <% end %>
  </tbody>
</table>
<% end %>

app/views/teachers/new.html.erb
<h1>New Teacher</h1>

<%= render partial: "layouts/errors", locals: {object: @teacher} %>
<%# this will render the errors partial and then send our original variable to the "object" variable in the form%>

<%= render 'form' %>

app/views/teachers/show.html.erb
<h1><%= full_name(@teacher)%>'s Page - <%= @teacher.user.school %> Teacher </h1>
<br>

<h6><strong>Current Subject:</strong> <%= @teacher.subject %></h6>
<h6><strong>Favorite Pastime:</strong> <%= @teacher.hobby %></h6>

<%= link_to "Add New Assignment", new_teacher_assignment_path(@teacher), class:"btn btn-success btn-sm" %>
<br>
<br>
<% if @teacher.assignments == [] %>
    <h3><%= full_name(@teacher) %> currently has no student assignments</h3>     
<% else %>    
    <h3> List of Students and Assignments for <%= full_name(@teacher)%></h3> 
    
<table class="table table-striped table-hover">
  <thead class="table-dark" >
    <tr>
      <th>Student Name</th>
      <th>Student Grade</th>
      <th>Assignment Title</th>
      <th>Assignment Content</th>
      <th>Assignment Due Date</th>
      <th>Completed?</th>
      <th>Assignment Grade</th>
      <th colspan="6"></th>
    </tr>
  </thead>

  <tbody>
    <% @teacher.assignments.each do |assignment| %>
      <tr>
        <td><%= full_name(assignment.student) %></td>
        <td><%= assignment.student.grade_level %></td>
        <td><%= assignment.title %></td>
        <td><%= assignment.content %></td>
        <td><%= assignment.due_date.strftime("%m/%d/%y") %></td>
        <td><%= assignment.completed %></td>
        <td><%= assignment.letter_grade %></td>
        <td><%= link_to "Assignment Page", assignment_path(assignment), class:"btn btn-success btn-sm" %></td>
        <td><%= link_to "Student Page", student_path(assignment.student), class:"btn btn-success btn-sm" %></td>  
      </tr>
    <% end %>
  </tbody>
</table>
<% end %>

<br>
<br>

<%= link_to "Edit #{full_name(@teacher)}", edit_teacher_path(@teacher), class:"btn btn-info btn-sm" %>
<br>
<br>
<%= link_to "Delete #{full_name(@teacher)}", @teacher, method: :delete, data: { confirm: "Please confirm deletion of #{full_name(@teacher)}"}, class:"btn btn-dark btn-sm" %>
<br>