config/routes.rb
Rails.application.routes.draw do
    
  root 'sessions#home'
  
  get '/signup' => "users#new"
  
  #login routes
  get '/login' => "sessions#new"
  post '/login' => "sessions#create"

  #logout route
  delete '/logout' => "sessions#destroy"
  
  #omniauth callback route
  get '/auth/google_oauth2/callback' => 'sessions#omniauth'

  #if you want more than one third party verification, you need to have a dynamic :provider...
  # get '/auth/:provider/callback' => 'sessions#omniauth'
  
  resources :users
  
  resources :teachers do
    resources :assignments, only: [:new, :create, :index]
    
  end
  
  resources :students do
    resources :assignments, only: [:index]
  end
  
  resources :assignments

  #scope method routes
  get '/alpha' => 'assignments#alpha'
  get '/overdue_assignments' => 'assignments#overdue_assignments'
end

app/views/layouts/_errors.html.erb
<%#  this partial code could be done as a helper, but would be difficult to write
because helper files are only coded in ruby and this has a lot of html tags %>

<% if object.errors.any? %>
  <div id="error_explanation">
    <h2><%= pluralize(object.errors.count, "error") %> prohibited this from being saved:</h2>

    <ul>
      <% object.errors.each do |error| %>
        <li><%= error.full_message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

<%#  using 'object' allows us to use this code repeatedly for all of the views we want %>

app/views/layouts/_header.html.erb
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  <div class="container-fluid">
    
    <%= link_to "Principal Principle App", user_path(current_user), class:"navbar-brand" if logged_in? %> 
    <!-- <a class="navbar-brand" href="#">Principal Principle App</a> -->
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        

        
        <li class="nav-item">
          <%= link_to "Create Teacher", new_teacher_path, class:"nav-link" if logged_in? %>
        </li>

        <li class="nav-item">
          <%= link_to "Create Student", new_student_path, class:"nav-link" if logged_in? %>
        </li>

        <li class="nav-item">
          <%= link_to "Overdue Assignments", overdue_assignments_path, class:"nav-link" if logged_in? %>
        </li>
        
        <li class="nav-item">
          <%if logged_in? %>
          <a class="nav-link" href="#">Honor Roll Students</a>
          <% end %>
        </li>

        <li class="nav-item">
            <%= link_to "Logout", logout_path, class:"nav-link", method: :delete if logged_in? %> 
        </li>    

        <li class="nav-item">
            <%= link_to "Log In", login_path, class:"nav-link" if !logged_in? %> 
        </li> 
            
      

      
      </ul>
      
    </div>
  </div>
</nav>

app/views/layouts/application.html.erb
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- Bootstrap CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-BmbxuPwQa2lc/FVzBcNJ7UAyJxM6wuqIj61tLrc4wSX0szH/Ev+nYRRuWlolflfl" crossorigin="anonymous">

    <title>Principal Principle</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
  <body>

    <%= render 'layouts/header' %>
    <div class="container">
      <br>
      <%= yield %>

    </div>

    <!-- Optional JavaScript; choose one of the two! -->

    <!-- Option 1: Bootstrap Bundle with Popper -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta2/dist/js/bootstrap.bundle.min.js" integrity="sha384-b5kHyXgcpbZJO/tY9Ul7kGkf1S0CWuKcCD38l8YkeH8z8QjE0GmW1gYU5S9FOnJ0" crossorigin="anonymous"></script>

    <!-- Option 2: Separate Popper and Bootstrap JS -->
    <!--
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.6.0/dist/umd/popper.min.js" integrity="sha384-KsvD1yqQ1/1+IA7gi3P0tyJcT3vR+NdBTt13hSJ2lnve8agRGXTTyNaBYmCR/Nwi" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta2/dist/js/bootstrap.min.js" integrity="sha384-nsg8ua9HAw1y0W1btsyWgBklPnCUAFLuTMS2G72MMONqmOymq585AcH49TLBQObG" crossorigin="anonymous"></script>
    -->
  </body>
</html>